fix: lighthouse .yaml

diff --git a/.github/workflows/lighthouse-action.yaml b/.github/workflows/lighthouse-action.yaml
--- a/.github/workflows/lighthouse-action.yaml
+++ b/.github/workflows/lighthouse-action.yaml
@@ -9,8 +9,13 @@ jobs:
         uses: actions/setup-node@v1
         with:
           node-version: 18.x
-      - run: npm install && npm install -g @lhci/cli@0.6.x
-      - run: npm run build
-      - run: lhci autorun
+      - name: npm install, build
+        run: |
+          yarn
+          npm run build
+      - name: run Lighthouse CI
+        run: |
+          npm install -g @lhci/cli@0.3.x
+          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
         env:
           LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
